package cmd

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/rafaelromao/sandman/internal/batch"
	"github.com/rafaelromao/sandman/internal/config"
	"github.com/rafaelromao/sandman/internal/events"
	"github.com/rafaelromao/sandman/internal/github"
	"github.com/rafaelromao/sandman/internal/prompt"
)

func init() {
	_ = os.Setenv("TMPDIR", "/tmp")
}

func initRunIntegrationRepo(t *testing.T, dir string) {
	t.Helper()

	cmds := [][]string{
		{"git", "init"},
		{"git", "config", "user.email", "test@test.com"},
		{"git", "config", "user.name", "Test"},
		{"git", "checkout", "-b", "main"},
		{"git", "commit", "--allow-empty", "-m", "init"},
	}
	for _, cmd := range cmds {
		c := exec.Command(cmd[0], cmd[1:]...)
		c.Dir = dir
		if out, err := c.CombinedOutput(); err != nil {
			t.Fatalf("%v: %s", err, out)
		}
	}
}

func runGit(t *testing.T, dir string, args ...string) string {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git %s: %v: %s", strings.Join(args, " "), err, out)
	}
	return string(out)
}

func initRunIntegrationRepoWithRemote(t *testing.T, dir string) string {
	t.Helper()
	initRunIntegrationRepo(t, dir)

	remoteDir := t.TempDir()
	cmd := exec.Command("git", "init", "--bare")
	cmd.Dir = remoteDir
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("init bare remote: %v: %s", err, out)
	}

	addRemote := exec.Command("git", "remote", "add", "origin", remoteDir)
	addRemote.Dir = dir
	if out, err := addRemote.CombinedOutput(); err != nil {
		t.Fatalf("add origin remote: %v: %s", err, out)
	}

	push := exec.Command("git", "push", "-u", "origin", "main")
	push.Dir = dir
	if out, err := push.CombinedOutput(); err != nil {
		t.Fatalf("push main: %v: %s", err, out)
	}

	return remoteDir
}

func newRunIntegrationDepsWithAgent(agent config.Agent, gh *fakeGitHubClient) Dependencies {
	return newRunIntegrationDepsWithSandbox(agent, "worktree", gh)
}

func newRunIntegrationDeps(agentCommand string, gh *fakeGitHubClient) Dependencies {
	return newRunIntegrationDepsWithAgent(config.Agent{
		Name:    "test-agent",
		Command: agentCommand,
	}, gh)
}

func executeRunCommand(t *testing.T, deps Dependencies, args ...string) (string, error) {
	t.Helper()

	var buf bytes.Buffer
	cmd := NewRunCmd(deps)
	cmd.SetOut(&buf)
	cmd.SetErr(&buf)
	cmd.SetArgs(args)

	err := cmd.Execute()
	return buf.String(), err
}

func waitForLineCount(t *testing.T, path string, want int) {
	t.Helper()
	for i := 0; i < 300; i++ {
		data, err := os.ReadFile(path)
		if err == nil && len(strings.Split(strings.TrimSpace(string(data)), "\n")) >= want {
			return
		}
		time.Sleep(20 * time.Millisecond)
	}
	t.Fatalf("timed out waiting for %d lines in %s", want, path)
}

func waitForPath(t *testing.T, path string) {
	t.Helper()
	for i := 0; i < 3000; i++ {
		if _, err := os.Stat(path); err == nil {
			return
		}
		time.Sleep(20 * time.Millisecond)
	}
	t.Fatalf("timed out waiting for %s", path)
}

// findFirstRunLog returns the bytes of the first run.log file found under
// <dir>/.sandman/batches/<batchID>/runs/<runID>/run.log. The batch and run
// IDs are generated by the orchestrator at run time, so tests that need to
// inspect agent output cannot hardcode them.
func findFirstRunLog(t *testing.T, dir string) ([]byte, error) {
	t.Helper()
	return findFirstRunLogBytes(dir)
}

func findFirstRunLogBytes(dir string) ([]byte, error) {
	batchesDir := filepath.Join(dir, ".sandman", "batches")
	entries, err := os.ReadDir(batchesDir)
	if err != nil {
		return nil, err
	}
	for _, batch := range entries {
		if !batch.IsDir() {
			continue
		}
		runsDir := filepath.Join(batchesDir, batch.Name(), "runs")
		runEntries, err := os.ReadDir(runsDir)
		if err != nil {
			continue
		}
		for _, run := range runEntries {
			if !run.IsDir() {
				continue
			}
			logPath := filepath.Join(runsDir, run.Name(), "run.log")
			if data, err := os.ReadFile(logPath); err == nil {
				return data, nil
			}
		}
	}
	return nil, os.ErrNotExist
}

// findRunLogForIssue searches .sandman/batches/ for the run.log of a specific
// issue by matching the run directory suffix (<shortid>-<ts>-<issue>). It
// fatally fails when no matching run log is found.
func findRunLogForIssue(t *testing.T, dir string, issue int) string {
	t.Helper()
	batchesDir := filepath.Join(dir, ".sandman", "batches")
	batches, err := os.ReadDir(batchesDir)
	if err != nil {
		t.Fatalf("list batches dir: %v", err)
	}
	suffix := fmt.Sprintf("-%d", issue)
	for _, batch := range batches {
		if !batch.IsDir() {
			continue
		}
		runsDir := filepath.Join(batchesDir, batch.Name(), "runs")
		runs, err := os.ReadDir(runsDir)
		if err != nil {
			continue
		}
		for _, run := range runs {
			if !run.IsDir() {
				continue
			}
			if strings.HasSuffix(run.Name(), suffix) {
				return filepath.Join(runsDir, run.Name(), "run.log")
			}
		}
	}
	t.Fatalf("run log not found for issue %d under %s", issue, batchesDir)
	return ""
}

func podmanAvailable(t *testing.T) bool {
	t.Helper()
	cmd := exec.Command("podman", "version")
	if err := cmd.Run(); err != nil {
		t.Skip("podman not available")
		return false
	}
	return true
}

type recordingEventLog struct {
	mu     sync.Mutex
	events []events.Event
	// errs is an optional per-call error queue. When set, each Log call
	// returns the head of the queue (advancing on each call) instead of
	// nil. Used by tests that need to assert the call site surfaces a
	// write failure rather than silently discarding it.
	errs []error
}

func (l *recordingEventLog) Log(event events.Event) error {
	l.mu.Lock()
	defer l.mu.Unlock()
	l.events = append(l.events, event)
	if len(l.errs) == 0 {
		return nil
	}
	err := l.errs[0]
	if len(l.errs) > 1 {
		l.errs = l.errs[1:]
	}
	return err
}

func (l *recordingEventLog) Read() ([]events.Event, error) {
	l.mu.Lock()
	defer l.mu.Unlock()
	return append([]events.Event(nil), l.events...), nil
}

func (l *recordingEventLog) RemoveEventsByIssue(issueNumber int) error {
	l.mu.Lock()
	defer l.mu.Unlock()
	var kept []events.Event
	for _, e := range l.events {
		if e.Issue == issueNumber {
			continue
		}
		if e.IssueRef != nil && *e.IssueRef == issueNumber {
			continue
		}
		kept = append(kept, e)
	}
	l.events = kept
	return nil
}

func writeSandmanDockerfile(t *testing.T, dir string) {
	t.Helper()
	dockerfileDir := filepath.Join(dir, ".sandman")
	if err := os.MkdirAll(dockerfileDir, 0755); err != nil {
		t.Fatalf("create .sandman dir: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dockerfileDir, "Dockerfile"), []byte("FROM alpine\n"), 0644); err != nil {
		t.Fatalf("write .sandman/Dockerfile: %v", err)
	}
}

func newRunIntegrationDepsWithSandbox(agent config.Agent, sandboxMode string, gh *fakeGitHubClient) Dependencies {
	return newRunIntegrationDepsWithSandboxAndGit(agent, sandboxMode, config.GitConfig{BaseBranch: "main"}, gh)
}

func newRunIntegrationDepsWithSandboxAndGit(agent config.Agent, sandboxMode string, gitCfg config.GitConfig, gh *fakeGitHubClient) Dependencies {
	if agent.Command == "" {
		agent.Command = "true"
	}
	binDir, err := os.MkdirTemp("", "sandman-agent-bin-")
	if err != nil {
		panic(err)
	}
	script := "#!/bin/sh\nset -e\n" + renderShellExports(agent.Env) + strings.TrimSpace(agent.Command) + "\n"
	for _, name := range []string{"opencode"} {
		path := filepath.Join(binDir, name)
		if err := os.WriteFile(path, []byte(script), 0755); err != nil {
			panic(err)
		}
	}
	_ = os.Setenv("PATH", binDir+":"+os.Getenv("PATH"))
	if gitCfg.BaseBranch == "" {
		gitCfg.BaseBranch = "main"
	}

	store := &fakeStore{config: &config.Config{
		DefaultAgent:  "opencode",
		Agent:         "opencode",
		ReviewCommand: "/oc review",
		WorktreeDir:   ".sandman/worktrees",
		Sandbox:       sandboxMode,
		Git:           gitCfg,
		AgentProviders: map[string]config.Agent{
			"opencode": {Command: agent.Command, Env: agent.Env},
		},
	}}

	runner := batch.NewOrchestrator(gh, &prompt.Engine{}, store, nil)
	return Dependencies{
		BatchRunner:  runner,
		ConfigStore:  store,
		EventLog:     &fakeEventLog{},
		GitHubClient: gh,
		Renderer:     &prompt.Engine{},
		IsTTY:        func() bool { return false },
		RepoRoot:     ".",
	}
}

func renderShellExports(env map[string]string) string {
	if len(env) == 0 {
		return ""
	}
	keys := make([]string, 0, len(env))
	for key := range env {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var out strings.Builder
	for _, key := range keys {
		out.WriteString("export ")
		out.WriteString(key)
		out.WriteString("=")
		out.WriteString(shellQuote(env[key]))
		out.WriteString("\n")
	}
	return out.String()
}

func shellQuote(value string) string {
	if value == "" {
		return "''"
	}
	return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'"
}

func issueAwareAgentCommand(body string) string {
	return strings.TrimSpace(`
# The agent command is shared across AgentRuns, so infer the issue number
# from the worktree directory each run executes inside.
repo_root=$(dirname "$(dirname "$(dirname "$(dirname "$PWD")")")")
issue_dir=$(basename "$PWD")
issue=${issue_dir%%-*}
` + body)
}

func podmanGitIdentityDeps(t *testing.T, dir, remoteDir, dotGitConfig, xdgGitConfig, agentCmd string) Dependencies {
	t.Helper()
	if err := os.MkdirAll(filepath.Join(dir, ".sandman"), 0755); err != nil {
		t.Fatalf("create .sandman dir: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, ".sandman", "Dockerfile"), []byte("FROM alpine\nRUN apk add --no-cache git\n"), 0644); err != nil {
		t.Fatalf("write .sandman/Dockerfile: %v", err)
	}

	homeDir, err := os.MkdirTemp("", "sandman-podman-home-")
	if err != nil {
		t.Fatalf("create home dir: %v", err)
	}
	t.Cleanup(func() { _ = os.RemoveAll(homeDir) })
	if err := os.MkdirAll(filepath.Join(homeDir, ".ssh"), 0755); err != nil {
		t.Fatalf("create ssh dir: %v", err)
	}
	gitCfg := fmt.Sprintf(dotGitConfig, "file://"+remoteDir)
	if err := os.WriteFile(filepath.Join(homeDir, ".gitconfig"), []byte(gitCfg), 0644); err != nil {
		t.Fatalf("write gitconfig: %v", err)
	}
	if strings.TrimSpace(xdgGitConfig) != "" {
		gitConfigDir := filepath.Join(homeDir, ".config", "git")
		if err := os.MkdirAll(gitConfigDir, 0755); err != nil {
			t.Fatalf("create xdg git dir: %v", err)
		}
		if err := os.WriteFile(filepath.Join(gitConfigDir, "config"), []byte(xdgGitConfig), 0644); err != nil {
			t.Fatalf("write xdg git config: %v", err)
		}
	}
	t.Setenv("HOME", homeDir)
	t.Setenv("XDG_CONFIG_HOME", filepath.Join(homeDir, ".config"))
	if out, err := exec.Command("podman", "run", "--rm", "alpine", "echo", "ok").CombinedOutput(); err != nil {
		t.Fatalf("warm podman image for test home: %v: %s", err, out)
	}

	gh := &fakeGitHubClient{
		issues: map[int]*github.Issue{
			42: {Number: 42, Title: "Fix bug", Body: "Users cannot log in."},
		},
		prs: map[string]*github.PR{"42-fix-bug": {Number: 42, State: "closed", Merged: true, HeadRefName: "42-fix-bug"}},
	}

	return newRunIntegrationDepsWithSandboxAndGit(config.Agent{Name: "test-agent", Command: strings.TrimSpace(agentCmd)}, "podman", config.GitConfig{BaseBranch: "main"}, gh)
}
